title: Title of your CV site
profile_img: /assets/img/keshab.jpg
icon_img: /assets/img/icon.webp

name: "Keshab Budhathoky"
job: "Lead/Senior DevOps Engineer"

address: Winchester, VA 22602, USA
email: kb4it.professional@gmail.com
linkedin_username: keshab-budhathoky-sendevopseng
github_username: keshabb
instagram_username: instagram
twitter_username: twitter
youtube_username: youtube
blog_url: homepage-url

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag