title: Title of your CV site
profile_img: /assets/img/keshab.jpg
icon_img: /assets/img/icon.webp

name: "Keshab Budhathoky"
job: "DevOps Engineer"

address: Winchester, VA 22602, USA
email: kbudhathoky@gmail.com
linkedin_username: keshab-budhathoky-sendevopseng
github_username: keshabb
twitter_username: KBudhathoky
youtube_username: ITTechMonk
blog_url: https://keshabb.blogspot.com/
# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag